name: woomera
version: 2.2.1
description: HTTP request dispatch and session manager
homepage: https://github.com/hoylen/woomera
author: Hoylen Sue <hoylen@hoylen.com>

environment:
  sdk: '>=1.13.0 <2.0.0'

dev_dependencies:
  test: ">=0.12.10 <1.4.0"

dependencies:
  logging: ">=0.11.2 <0.11.4"
  uuid: ">=0.5.0 <1.1.0"
