name: woomera
version: 3.0.2
description: Web framework for handling HTTP requests, managing sessions and generating responses
homepage: https://github.com/hoylen/woomera
author: Hoylen Sue <hoylen@hoylen.com>

environment:
  sdk: '>1.9.9 <3.0.0'

  # sdk: '>=2.0.0 <3.0.0'
  # TODO: use the correct SDK specification (above) when pub.dartlang.org
  # starts using a production Dart 2 instead of Dart 2.0.0-dev.69.3.
  #
  # The "Issues and suggestions" says:
  #     Running pub upgrade failed with the following output:
  #     ERR: The current Dart SDK version is 2.0.0-dev.69.3.
  #     Because woomera requires SDK version >=2.0.0 <3.0.0, version solving failed.

dev_dependencies:
  test: ">=0.12.10 <1.4.0"

dependencies:
  logging: ">=0.11.2 <0.11.4"
  uuid: ">=0.5.0 <1.1.0"
