name: woomera
version: 4.0.0
description: Web framework for handling HTTP requests, managing sessions and generating responses
homepage: https://github.com/hoylen/woomera
author: Hoylen Sue <hoylen@hoylen.com>

environment:
  sdk: '2.0.0'
  # sdk: '>=2.x.x <3.0.0'
  # Note: does NOT work with these versions of Dart, since they have a bug
  # that prevents cookies from being deleted:
  # - Dart 2.1.0
  # - Dart 2.1.1
  # - Dart 2.2.0

dev_dependencies:
  test: ">=0.12.10 <1.4.0"

dependencies:
  logging: ">=0.11.2 <0.11.4"
  uuid: ">=0.5.0 <1.1.0"
