name: woomera
version: 5.4.0
description: "Framework for implementing Web servers: handling HTTP requests, managing sessions and generating responses"
homepage: https://github.com/hoylen/woomera

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ">=0.12.10 <2.0.0"

dependencies:
  http: "^0.12.2"
  logging: ">=0.11.2 <0.11.5"
  uuid: ">=2.1.0 <3.0.0"
