name: woomera
version: 7.0.1
description: "Framework for implementing Web servers: handling HTTP requests, managing sessions and generating responses"
homepage: https://github.com/hoylen/woomera

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: '^0.13.0'
  logging: '^1.0.1'
  uuid: '^3.0.3'

dev_dependencies:
  test: ">=0.12.10 <2.0.0"
