name: woomera
version: 4.0.1
description: Web framework for handling HTTP requests, managing sessions and generating responses
homepage: https://github.com/hoylen/woomera
author: Hoylen Sue <hoylen@hoylen.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ">=0.12.10 <1.4.0"

dependencies:
  http: "^0.12.0+1"
  logging: ">=0.11.2 <0.11.4"
  uuid: ">=0.5.0 <1.1.0"
